#! /opt/homebrew/bin/fish

osascript -e 'tell application "Finder" to set desktop picture to alias ((path to pictures folder as text) & "wallpaper.png")'
rm /var/folders/*/*/*/com.apple.dock.iconcache
killall Dock

brew update
brew bundle --global
brew upgrade
brew cleanup
brew bundle dump --global -f

# Install / Bootstrap:
# - Install YADM + pull branch
# - Install Homebrew + packages
