#!/usr/bin/env sh

spacebar -m config position             bottom
spacebar -m config height               26
spacebar -m config title                on
spacebar -m config spaces               off
spacebar -m config clock                on
spacebar -m config power                off
spacebar -m config padding_left         20
spacebar -m config padding_right        20
spacebar -m config spacing_left         25
spacebar -m config spacing_right        15
spacebar -m config text_font            "FiraCode Nerd Font Mono:Retina:12.0"
spacebar -m config icon_font            "FiraCode Nerd Font Mono:Regular:12.0"
spacebar -m config background_color     0xff282a36
spacebar -m config foreground_color     0xffeff0eb
#spacebar -m config space_icon_color     0xff458588
spacebar -m config power_icon_color     0xffcd950c
spacebar -m config battery_icon_color   0xffd75f5f
spacebar -m config dnd_icon_color       0xffa8a8a8
spacebar -m config clock_icon_color     0xffa8a8a8
spacebar -m config power_icon_strip      
spacebar -m config clock_icon           " "
spacebar -m config dnd_icon             
spacebar -m config clock_format         "%d/%m/%y (%a)   %I:%M%p"
spacebar -m config left_shell          on
spacebar -m config left_shell_icon     " "     
spacebar -m config left_shell_command  "whoami"

echo "spacebar configuration loaded.."
